name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Publish the application
    - name: Publish the application
      run: dotnet publish "./src/NomadIIS/NomadIIS.csproj" /p:PublishProfile="./src/NomadIIS/Properties/PublishProfiles/Release.pubxml"

    # Upload the artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binary
        path: "./src/NomadIIS/bin/Release/net7.0/publish/nomad_iis.exe"
